name: Create Environment

on:
  push:
    branches:
      - '**'  # Triggers on any branch push
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  create-environment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy TODO App to VM
      run: |
        echo "Deploying TODO app to Azure VM..."
        # Add your deployment commands here
        # For example, copying files to VM, restarting web server, etc.